### ISSUE TITLE
프로젝트 명을 DaligiEngine으로 바꾸시는게 어떨까요?

### ISSUE THREAD

**Issue by dalinaum** [zho7611/dg#1]
로컬에 클론을 받거나 포크를 받을때 dg라고만 나와 있으면 좀 기분이 어색할 것 같습니다. 이름을 아려고 해도 읽어봐야만 하고요. 프로젝트 명을 dg 대신에 풀 네임으로 바꾸는 것이 어떨까요? :)

**Comment by zho7611** [comment]
의견 감사드립니다. 그 생각을 못 했군요. 개인적으로 오랫동안 사용하던 이름이라 저만 익숙했었군요. 이 이름으로 링크를 많이 뿌려놔서 당분간은 힘들 것 같습니다. 다음 메이저 업데이트시에 고려하겠습니다. 혹시 기존의 이름도 유지하면서 새로운 이름으로 변경할 수 있나요? github 는 처음이라..

**Comment by dalinaum** [comment]
아마 기존의 이름을 유지하면서 바꾸기는 어려울거에요. 아무튼 좋은 프로젝트 공유 감사드립니다.
